### PR TITLE
Bugfix p0size parameter mutation + minimized support on modal backdrop

### PR DESCRIPTION
**Pull request by rguihard**
Changes are describe in CHANGELOG.md (proposal)

- Responsive behaviour on panel width with option "responsive"
- Hide/show methods for panel reuse, in case of static content (ex: 
helper popup) to avoid excessive DOM manipulation
- set/get/remove content to update reusable panel layout

### CODE REVIEW

**Comment by Flyer53** [comment]
@rguihard 
Hi there ... and thank you very much for your work and proposal.

It will definitely take some time time to go over all this stuff. In the course of doing this I'll most probably comment one thing after the other here in order to discuss one thing at a time.

So please be patient. And I hope you're willing to discuss your changes/additions with me here.

Best regards,
Stefan

**Comment by rguihard** [comment]
Hello,

I intend to implement this librairy in a project. For that purpose i need to make some changes.
I could use the existing [extend](https://jspanel.de/#global/extend) method to cover some of my needs, but i think it could be some nice features for other people.

I tried to describe each change in the CHANGELOG.md, but of course, discuss about the reason of those change will help you to understand them.

Thank you

**Comment by Flyer53** [comment]
**Let's start with discussing your added option `responsive`**

As far as I see it this can be achieved quite easily already. Options `contentSize` and `panelSize` both accept functions for the parameters **_width_** and _**height**_ in order to accomodate specific needs. So a panel configuration like ...
```javascript
jsPanel.create({
  panelSize: {
    width: function() {
      let w = 800, // = primarily intended panel width
          ww = window.innerWidth;
      return w < ww ? w : ww;
    },
    height: 400
  }
});
```
... would set the panels width to window width if the panel dimensions would otherwise overflow the window. The same approach would work for height as well of course.

If a panel needs to respond to a window resize event it wouldn't be a big thing to set up an `onwindowresize` event handler.

Do I miss something?

Notes:
+ One of my goals is to keep the code base as small as possible. So I tend not to add options whose purpose can be achieved easily without adding extra code to the main script.
+ If there was an option `responsive` it would need to work also in use cases where option `container` is set to something other than `'window'`.

**Comment by rguihard** [comment]
I like your solution, but i encounter a issue with the pOsize method. The size parameter (contentSize or panelSize) attributes are modified during the execution. So the `width: () => xxx` become `width : xxx px` for the rest of panel life.
With a Object.assign on a new dedicated object, it works great
```
pOsize(panel, size) {
let values = Object.assign({}, size || this.defaults.contentSize);
[...]
```

What do you think about this code addition in default windowResizeHandler : 
```
+ self.setSize();
```
In case of a fixed width panelSize/contentSize, there is no change, but in case of a computed width property, the window resize event will trigger a size adjustment

**Comment by Flyer53** [comment]
Hi Rémy, one issue settled 👍 
However, concerning the window resize handler: did you take a look at the method [overlaps()](https://jspanel.de/#methods/overlaps)? It gives you quite some information about a panel's position relative to another element or the window.

> What do you think about this code addition in default windowResizeHandler :
> + self.setSize();

Well, I thought about something similar a few times but decided against manipulating panel size on window resize because it causes more problems than it solves.
+ What if you as developer deliberately disable the `resizeit` feature?
+ What if panel content is such that a certain panel size (or even aspect ratio) is required?
+ What if a user resized a panel manually already?

Even if I try to consider all this the resulting panel size will most probably not be the best one.I don't think it's possible to find a solution that fits everyones needs. Only you as developer know the specific needs of your app. So I think it's better to set up your own window resize handler if resizing a panel on window resize is required.

___
**Next topic: _show_/_hide_ methods you want to add**

What is so different in your app that you don't want to use the regular [minimize()](https://jspanel.de/#methods/minimize) and [normalize()](https://jspanel.de/#methods/normalize) methods to hide/show a panel?
And if you don't want the replacement element for the minimized panel in the lower left corner you can set option [minimizeTo](https://jspanel.de/#options/minimizeTo) to `false`. Then no replacement element for the minimized panel is created and you just have to call `normalize()` on the panel to get it back in view. By the way, a minimized panel ist not removed somehow, it's just moved off screen and thus still available for any kind of manipulation.

**Comment by rguihard** [comment]
Hi !

I'll read the documentation about overlaps, thank you

- [X]  For my last suggestion about calling "self.setSize()", i agree with your opinion, i can easily create my own "onWindowResize" function whose fits my specific need.

___

I want to create a panel which can not be close (= content destroy) by user, only by application.
I tried something like that : 
```
myPanel = jsPanel.create({
          minimizeTo: false,
          setStatus: 'minimized',
          content: 'Reusable panel hidden at creation time',
          closeOnEscape: () => {
            this.minimize();
          }
        });
```
In this configuration, my panel is hidden at creation time, but user still can close panel with control button.
So, i tried to override controls like that : 
```
jsPanel.create({
          minimizeTo: false,
          setStatus: 'minimized',
          content: 'Reusable panel hidden at creation time',
          closeOnEscape: () => {
            this.minimize();
          },
          headerControls: {
              minimize: 'remove',
              close: 'remove',
              smallify: 'remove'
          }
        }).addControl({
          html: '<svg focusable="false" class="jsPanel-icon" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 22 22"><path fill="currentColor" d="M13.7,11l6.1-6.1c0.4-0.4,0.4-0.9,0-1.3l-1.4-1.4c-0.4-0.4-0.9-0.4-1.3,0L11,8.3L4.9,2.3C4.6,1.9,4,1.9,3.7,2.3L2.3,3.7 C1.9,4,1.9,4.6,2.3,4.9L8.3,11l-6.1,6.1c-0.4,0.4-0.4,0.9,0,1.3l1.4,1.4c0.4,0.4,0.9,0.4,1.3,0l6.1-6.1l6.1,6.1 c0.4,0.4,0.9,0.4,1.3,0l1.4-1.4c0.4-0.4,0.4-0.9,0-1.3L13.7,11z"/></svg>',
          name: 'hide',
          ariaLabel: 'panel hide',
          handler: (panel, control) => {
            panel.minimize();
          },
          position: 6
        });
```
But i didn't found how to avoid close action on "closeChildpanels" in case of panel superposition.

**Comment by Flyer53** [comment]
Ok, your second example should work reasonably well.
Just one thing: option `closeOnEscape` accepts only boolean `true` or `false`. A function causes an error. And if you don't want the user to be able to close a panel you can't use option `closeOnEscape` anyhow.

What I don't understand is ...
> But i didn't found how to avoid close action on "closeChildpanels" in case of panel superposition.

... and I ask you to explain exactly what you really mean. The term _**childpanel**_, as I use it, applies only to panels which are appended to the content section of another panel.

___
**Next topics:**

+ **new method `getContent()`**
I don't think that such a method is needed because every panel has the property `content` which returns the `<div class="jsPanel-content">` containing all content.
If you need the content without the surrounding `<div>` use `panel.content.innerHTML` for example. That gives you a **DOMString** of all content. In order to get a **DocumentFragment** use `var content = jsPanel.strToHtml(panel.content.innerHTML)` for example.
+ **new method `setContent()`**
There are so many ways to update, delete, append, prepend or otherwise alter panel content that I really don't know how I could set up a general method doing all this to everybody's satisfaction. Native JavaScript already offers all you need to do whatever operation is required. And for your application you know best what is required ...
Then there already are the methods [jsPanel.ajax()](https://jspanel.de/#global/ajax) and [jsPanel.fetch()](https://jspanel.de/#global/fetch) you could use for example.
+ **rename method `contentRemove()` to `removeContent()`**
I can't do this because it would break existing code.

**Comment by rguihard** [comment]
The existing source code accepts a function or boolean for "closeOnEscape"
```
                            if (item.options.closeOnEscape) {
                                if (typeof item.options.closeOnEscape === 'function') {
                                    return item.options.closeOnEscape.call(item, item);
                                    // if return value is falsy next panel in sequence will close, otherwise processing of Array.prototype.some() stops
                                } else {
                                    item.close(null, true);
                                    return true;
                                }
                            }
```
Ok, i mistunderstood what "childpanel" means. So i can cover all my needs with minimize functionality.

___

I will use "extend" function to append my helpers set/get/remove content

___

Sooooo, i revert all my changes but 2 changes : 
- Fix on pOsize to avoid size parameter mutation
- Modal callbacks on minimize/normalize events in order to mask backdrop when modal panel is minimize (seems to not be covered yet)

**Comment by Flyer53** [comment]
Ups ... you're right on option `closeOnEscape`. Missed that when I wrote the new documentation pages. Sorry for that!

I'll look at the other two points over the weekend ...

**Comment by Flyer53** [comment]
**No 1:**

Well, there's nothing wrong with `pOsize()`
Currently the code is ...
```javascript
pOsize(panel, size) {
    let values = size || this.defaults.contentSize;
    // ....
}
```
... where the parameter **_size_ can be a string value or an object**. If you would use ...
```javascript
pOsize(panel, size) {
    let values = Object.assign({}, size || this.defaults.contentSize);
    // ....
}
```
... you couldn't use a string value anymore. Remember this is the value passed to option `contentSize` or option `panelSize` in the panel configuration. Again, this can be a string or an object.
Why? Because ...
```javascript
let values = Object.assign({}, size || this.defaults.contentSize);
// where size is a string value like '400px 300' for example
```
... would return the object ...
```javascript
{ 0: "4", 1: "0", 2: "0", 3: "p", 4: "x", 5: " ", 6: "3", 7: "0", 8: "0" }
```
... which is nothing the script can work with. Required is an object ...
```javascript
{ width: "400px", height: 300 }
// or
{ width: "400px", height: "300" }
```

**Comment by Flyer53** [comment]
**No 2, the modal extension:**
___
By definition a modal window is a user interface element that displays in front of and deactivates all other page content. **To return to the main content, the user _must_ engage with the modal by completing an action or by closing it.**
See https://blog.hubspot.com/website/modal-web-design
___
That's exactly not what you seem to intend with the "modal". You want to minimize it in order to do some other stuff returning to the panel at a later time if I get you right. But that's not the purpose of a modal window. To the contrary, I even tend to actively block the use of any other controls than the close button.

So for your application I would recommend you use a regular panel with all options available and implement your own way to add/remove a backdrop if needed. Or you simply adjust the modal extension to your needs. But I won't implement your changes in an official release, sorry!

**Comment by rguihard** [comment]
Hi,

**No 1 :**

You're right, my change doesn't works with a String size param. I can move the object assign in the "typeof" size test.
As a remember, i want to prevent this mutation 
```
var myPanel = jsPanel.create({ 
  content : 'Calc width', 
  panelSize : {
    width: function() {
      var w = 600;
      var ww = window.innerWidth;
      return ww < w ? ww : w; 	
    }
  },
  onwindowresize: true
});
console.log(myPanel.options.panelSize);
// Object { width: "600px", height: "600px" }
```

With a panel which uses a "windowresize" function and a function width/height for panelSize, the panelSize must be dynamically compute each time, isn't it ? 

**No 2 :**

Let's explain my user case.
This is a simple dashboard, where user can CRUD "tasks". A task is a simple reminder compose with a text note, a date and few others information.
When user wants to delete a not yet achieve task, i want to display a modal with a warning. If the user confirm this action, the task is effectively deleted, not otherwise. While the modal is visible, user can't interact with other elements.

I want to generate the warning modal only once, then reuse it each time.
My first intent was to append a new behaviour (show/hide functions). But after our discussion, i understood i can achieve the same thing with "minimize/normalize" existing methods (+ hide minimizeTo)
In result, when user cancels my modal, that calls "minimize" function, not "close" function. Later, this modal could be reuse with the "normalize" function.

The current modal code only offers "close" control in his default parameters.
My approach consists to use "minimize" control and make it usable in the configuration describe above.
It seems me to be a non regressive modification, there is no changes on the original behavior.

Have a nice day

**Comment by Flyer53** [comment]
Hi again ...

**No 1:**

When you implement a window resize handler that manipulates panel size you obviously need to do some calculation to get the desired panel size. This calculation repeats continuously while the window is being resized and thus the panel also needs to be resized continuously. Simple example:
```javascript
jsPanel.create({
  onwindowresize: function(event, panel) {
    // do the size calculation
    panel.resize(calculated_size); // where 'calculated_size' can be the same string or object as used with option contetSize/panelSize
  }
});
```
___

**No 2:**

When I get you right the only remaining issue is that you need to toggle the modal backdrop for your use case. This can be done quite easily with the current code base. Example:
```javascript
jsPanel.modal.create({
  id: 'modal-1', // with a known id you can identify the corresponding modal backrop
  headerControls: 'none', // reomve all controls and get back modified close control later
  minimizeTo: false, // disable the minimized panel replacement
  onminimized: function(panel, status){
    // temporarily remove the modal backdrop on minimize
    document.querySelector('#jsPanel-modal-backdrop-modal-1').style.display = 'none';
  },
  onnormalized: function(panel, status){
    // get back the modal backdrop on normalize
    document.querySelector('#jsPanel-modal-backdrop-modal-1').style.display = 'block';
  }
}).addControl({ // add a modified close control
  html: '<svg focusable="false" class="jsPanel-icon" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 22 22"><path fill="currentColor" d="M13.7,11l6.1-6.1c0.4-0.4,0.4-0.9,0-1.3l-1.4-1.4c-0.4-0.4-0.9-0.4-1.3,0L11,8.3L4.9,2.3C4.6,1.9,4,1.9,3.7,2.3L2.3,3.7 C1.9,4,1.9,4.6,2.3,4.9L8.3,11l-6.1,6.1c-0.4,0.4-0.4,0.9,0,1.3l1.4,1.4c0.4,0.4,0.9,0.4,1.3,0l6.1-6.1l6.1,6.1 c0.4,0.4,0.9,0.4,1.3,0l1.4-1.4c0.4-0.4,0.4-0.9,0-1.3L13.7,11z"/></svg>',
  name: 'hide',
  ariaLabel: 'panel hide',
  handler: (panel, control) => {
    panel.minimize();
  },
  position: 6
});
```
A quick test shows no problems and there is no need to adjust anything in the current codebase. And when you close the panel programatically using the regular `close()` method the modal backdrop is removed as well.
Unless I misunderstand you somehow this should do it.

**Comment by Flyer53** [comment]
@rguihard 
I updated the above exampe a little bit and my tests show no problems.

To sum up:
+ the "size responsiveness" is something you have to implement yourself as discussed. However, I see possibilities to improve option `onwindowresize`.
+ additional show/hide methods are not needed since that can be done quite easily with the current codebase.
+ additional methods to update/set/get/remove content are not reasonable (as already discussed).
+ renaming existing methods is not a good idea since it would break existing code. And one of your proposals to change the inner workings of a non-public method would have had the same result.
+ your proposed changes/additions to the modal extension stand in contrast to the general (and my) view of what a modal window represents and are not going to be part of an official release.

You put a lot of effort in your proposals. I do see that and really appreciate it.
But in order to accept a proposal I need to be convinced that it constitutes a benefit for a majority of users. Most of your proposals seem to be of little use for a majority of users or even unnecessary.
Concerning the modal extension I described my view above. However, I provided a code sample showing how you can achieve your idea with the current codebase.

So based on the notes above I cannot merge your pull request.

Regards,
Stefan

**Comment by rguihard** [comment]
Hi @Flyer53 

Thanks a lot for your reply.
Don't worry, I won't be offended if my pull request is declined :smile: 
This library is very powerful, and with existing features i can handle the majority of my users cases.

- About my additions in the modal extension to support "minimize", i need to keep them as long as i want to create my modal in background. Without those changes, backdrop is append at modal creation.
- For the "pOsize" modification, i reproduce what i consider an "issue". Inside "create" function, there is a call to "setSize()". This function call "pOsize" function with "options.panelSize" as parameter. If my panelSize width/height is a function, this property is updated by "pOsize" to become the result of this call. 
```
userPanelSize = {
    width: function() {
      var w = 600;
      var ww = window.innerWidth;
      return ww < w ? ww : w; 	
    },
   height: '600px'
  }
var panel = jsPanel.create({ panelSize: userPanelSize });
console.log(panel.options.panelSize)
// Object { width: "600px", height: "600px" }
```

Yours sincerely,

**Comment by Flyer53** [comment]
@rguihard 
Glad to hear that 👍 

Concerning the modal extension you can of course make any changes you want in order to match your needs.

Concerning the methods `.pOsize()` and `.setSize()` you have to realize that they are intended only for internal use (that's why they are not part of the published API). That means you have to take into account that they might be subject to change without any notice. If you need to keep the function originally passed to width and/or height it shouldn't be a big thing to store it away somewhere for later use.

**Pull request closed without merging**
